# Restaurants End Point's
### Get all restaurants
GET http://localhost:5222/api/restaurants
Accept: application/json

### Get restaurant by id
GET http://localhost:5222/api/restaurants/4
Accept: application/json

### Delete Restaurant By Id
DELETE http://localhost:5222/api/Restaurants/4
Accept: application/json

### Create a new restaurant
POST http://localhost:5222/api/restaurants 
Content-Type: application/json
Accept: application/json

{
  "name": "Spice Garden",
  "description": "Authentic Indian cuisine with a modern twist",
  "category": "Indian",
  "hasDelivery": true,
  "contactEmail": "info@spicegarden.com",
  "contactNumber": "9876543210",
  "city": "Gadag",
  "street": "Main Road",
  "postalCode": "582101"
}
###

# Dishes End Point's
### Create Dishes
POST http://localhost:5222/api/restaurants/1/dishes
Content-Type: application/json
Accept: application/json

{
"name": "Paneer Butter Masala",
"description": "Rich and creamy North Indian curry",
"price": 250.00,
"kiloCalories": 600
}

### Get all the dishes from restaurants
GET http://localhost:5222/api/restaurants/1
Content-Type: application/json
Accept: application/json

### Get Dish By Id
GET http://localhost:5222/api/restaurants/1/dishes/1
Accept: application/json

